### ISSUE TITLE
Standard Return Code

### ISSUE THREAD

**Issue by StuckiSimon** [StuckiSimon/progc#2]
It is standard for CLIs and bash scripts to return non-zero return codes in case of error and `0` in case of success.

Therefore this snippet is not straightforward:
```
if (hasFailed == 1) {
  return 0;
}
return 1;
```
from [ss04-word-sort/src/main.c](https://github.com/StuckiSimon/progc/blob/master/ss04-word-sort/src/main.c#L73)

This does comply with the standard:
```
if (RETURN_CODE == 0) {
  // do sth in case of success
}
return RETURN_CODE;
```

One exception from this rule:
In case the name of the function is a predicate one can use "`boolean`s" to indicate truthiness.

**Comment by sir-marc** [comment]
Fixed by:
6ba8ce43a4afe8b910a514549d6574c4093b232a

**Comment by StuckiSimon** [comment]
Looks fine now
