### ISSUE TITLE
Malloc check Pointer

### ISSUE THREAD

**Issue by StuckiSimon** [StuckiSimon/progc#4]
There are unchecked calls to `malloc`.

E.g.:
https://github.com/StuckiSimon/progc/blob/27a4b49026e715e9b3dcae0dc0af09fc137f66b0/ss01-count-words-and-chars/src/main.c#L35

They must be checked using something like:

```c
if (pointer == NULL) {
  return EXIT_FAILURE;
}
```

**Comment by sir-marc** [comment]
Should be resolved by 4576ce4ff091246b0e6d0b2d16ed16e9a005dde4

**Comment by StuckiSimon** [comment]
Looks fine now
