### ISSUE TITLE
Use safe string operations

### ISSUE THREAD

**Issue by StuckiSimon** [StuckiSimon/progc#5]
Currently there are usages of unchecked string operations.

E.g.
https://github.com/StuckiSimon/progc/blob/3ae64b893010eba3e0eb5aa310643a92395d472d/ss04-word-sort/src/main.c#L25

See this [stackoverflow](https://stackoverflow.com/questions/30190460/advantages-of-strncmp-over-strcmp) question.

One should therefore use
`strncmp` instead of `strcmp`
`strncpy` instead of `strcpy`
and so on...

**Comment by sir-marc** [comment]
Should be resolved by 20dc33e6d55376d6eb3f345315672a1013e3846d

**Comment by StuckiSimon** [comment]
Maybe it was unclear, but I did not mean this is the only occurence.
See:
https://github.com/StuckiSimon/progc/blob/4576ce4ff091246b0e6d0b2d16ed16e9a005dde4/ss02-datum-validator/src/main.c#L27

**Comment by sir-marc** [comment]
c61320a1cff06c6c0b0ed3b728497438b47ef706

I couldn't spot any other str functions with a strn alternative.
If you should find some, I'm sorry and would appreciate a hint again.

**Comment by StuckiSimon** [comment]
Looks fine now
