### ISSUE TITLE
Underscores shall be used to separate words in names

### ISSUE THREAD

**Issue by StuckiSimon** [StuckiSimon/progc#6]
According to the code style guide:

> Underscores shall be used to separate words in names e.g. count_active_users()

Currently the method names use camel case.

**Comment by sir-marc** [comment]
This should be resolved by the last commits

**Comment by StuckiSimon** [comment]
Please reference the commit, otherwise I have to look up the corresponding commit.

**Comment by sir-marc** [comment]
This issue should be fixed by multiple commits:
007fb76aa7d097183d29049c9e965f2a622daf56
4354c1476343548188776ead3775af571ee3d9b0
7252aa433c7194d0223c27e757ec7a7f0a1ab2d7
724ac3ed566a67528e5da20fa3c3cdea1c208544
6ba8ce43a4afe8b910a514549d6574c4093b232a

**Comment by StuckiSimon** [comment]
Looks fine now
