### ISSUE TITLE
Add phony targets to makefile

### ISSUE THREAD

**Issue by StuckiSimon** [StuckiSimon/progc#7]
Currently no Makefile uses phony targets. This especially affects the `make doc` command.

Therefore proper phony targets must be configured.

e.g.:

```
.PHONY: doc
```

Check out this nice documentation to see how and why phony targets are required: [https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html](https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html)

**Comment by sir-marc** [comment]
dd71f469e383eff2867980d02804f3acd5fb582e

**Comment by StuckiSimon** [comment]
Looks fine now
